apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xelasticsearchservices.azure.aksstack.upbound.io
spec:
  group: azure.aksstack.upbound.io
  names:
    kind: XElasticSearchServices
    plural: xelasticsearchservices
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              operators:
                type: object
                description: Configuration for operators.
                properties:
                  elasticsearch:
                    type: object
                    description: Configuration for the elasticsearch operator.
                    properties:
                      version:
                        type: string
                        description: elasticsearch operator version to run.
              providerConfigRef:
                type: object
                description: "A reference to the ProviderConfig of the cluster that services should be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration.
                      This will typically be the name of the cluster with a
                      five character suffix appended."
                required:
                - name
            required:
            - providerConfigRef
