apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkeptnservices.azure.aksstack.upbound.io
  labels:
    plan: full
    provider: helm
spec:
  compositeTypeRef:
    apiVersion: azure.aksstack.upbound.io/v1alpha1
    kind: XKeptnServices
  resources:
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: keptn
            chart:
              # Note that default values are overridden by the patches below.
              name: keptn
              repository: https://charts.keptn.sh
              version: "1.2.0"
            values: {}
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-keptn"
        # All Helm releases derive their labels and annotations from the XR.
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        # All Helm releases derive the ProviderConfig to use from the XR.
        - fromFieldPath: spec.providerConfigRef.name
          toFieldPath: spec.providerConfigRef.name
        # Derive the keptn operator image and tag from the XR.
        - fromFieldPath: spec.operators.keptn.version
          toFieldPath: spec.forProvider.chart.version
        # Pass XR namespace to write connection secrets namespace
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
