apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: azure-aks-stack
  annotations:
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This is a PoC for a stack Configuration for AKS.
      It is a starting point to build, run, and operate your own aks cluster.
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-azure
      version: ">=v0.14.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.13.0"
